In [1]:
import pandas as pd

In [2]:

dataset=pd.read_csv("prep.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [5]:
independent=dataset[["bgr","bu","sc","pot","hrmo"]]

In [6]:
dependent=dataset[["classification"]]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [8]:
X_train

       bgr     bu    sc  pot       hrmo
92   210.0  165.0  18.0  4.7  12.518156
223  133.0   48.0   1.2  4.3  14.800000
234  255.0  132.0  12.8  5.7   7.300000
232  204.0   34.0   1.5  4.1   9.800000
336  158.0   85.0   3.2  3.5  10.100000
..     ...    ...   ...  ...        ...
323   98.0   86.0   4.6  3.4   9.800000
192  150.0   18.0   1.2  4.2  12.518156
117  107.0   15.0   1.0  4.2  11.800000
47    89.0   42.0   0.5  5.0  16.700000
172  129.0   25.0   1.2  5.0  17.200000

[279 rows x 5 columns]

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [10]:
X_train

array([[ 0.8058831 ,  2.00438397,  2.50033543,  0.05474947,  0.02340477],
       [-0.21742153, -0.23410906, -0.34458897, -0.12887486,  0.86422958],
       [ 1.40391827,  1.37301414,  1.61976359,  0.51381027, -1.89940589],
       ...,
       [-0.56295297, -0.86547889, -0.37845712, -0.17478094, -0.24122461],
       [-0.80216703, -0.34890357, -0.46312749,  0.19246771,  1.56435057],
       [-0.27058021, -0.6741547 , -0.34458897,  0.19246771,  1.74859293]])

In [11]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the target variable
y_train_encoded = label_encoder.fit_transform(y_train)

#y_test_encoded=label_encoder.fit_transform(y_train)

C:\Users\Manikandan\anaconda3\envs\ds\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [12]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor.fit(X_train,y_train_encoded)

SVR(C=1000)

In [13]:
y_pred=regressor.predict(X_test)

In [25]:
#y_pred
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

ValueError: could not convert string to float: 'no'

In [ ]:
import pickle
filename="Finalized_model_SKB-C_FS1.sav"

In [ ]:
preinput=([[109,39,1,48,9600]])
preinput

In [ ]:
pickle.dump(classifier,open(filename,'wb'))

In [ ]:
loaded_module=pickle.load(open("Finalized_model_SKB-C_FS1.sav",'rb'))

In [ ]:
result1=loaded_module.predict(preinput)
result1

In [ ]:
result1.astype(int)